import json, os
here = os.path.dirname(os.path.abspath(__file__))
html = open(os.path.join(here, "host", "control.html")).read()
bad = sorted({ch for ch in html if ord(ch) > 0xFFFF})
if bad:
    raise SystemExit("control.html has astral-plane chars the MicroPython freeze "
                     "cannot handle (surrogate pairs): " + " ".join(repr(c) for c in bad))
out = os.path.join(here, "device", "webui_controller.py")
with open(out, "w") as f:
    f.write("# GENERATED from host/control.html by tools_gen_controller.py — do not edit.\n")
    f.write("# Regenerated by build_firmware.sh before every build.\n")
    f.write("HTML = " + json.dumps(html) + "\n")
print("wrote", out, "(%d bytes of HTML)" % len(html))
